spring:
  config:
    import: "file:${scan.config}/scan-application.yml"

scan:
  # sample value, should be overridden in Spring command line properties, e.g. -Dscan.project=/work/project/scan-sample
  project: scan-project/sample
  config: "${scan.project}/config"

replace:
  defaultTemplate: "w{hash}"

write:
  folder: ${scan.project}/target/preview
  report: ${scan.project}/target/code-report.csv
  generatedReplacement: ${scan.project}/target/generated-replacement.csv
