spring:
  config:
    import: "file:${scan.config}/scan-application.yml"

scan:
  # sample value, should be overridden in Spring command line properties, e.g. -Dscan.project=/work/project/scan-sample
  project: scan-project/sample
  config: "${scan.project}/config"

read:
  threads: 10

replace:
  defaultTemplate: "w{hash}"

write:
  # Default is Review phase (false). After review is completed, to Cleanup Code add JVM parameter -Dwrite.inplace=true
  inplace: false
  folder: ${scan.project}/target/preview
  report: ${scan.project}/target/code-report.csv
  generatedReplacement: ${scan.project}/target/generated-replacement.csv

logging:
  file: ${scan.project}/target/logs/code-egress.log