read:
  folder: "."
  guard:
    values:
    patterns:
      - ".*"
  ignore:
    values:
      - "target"
      - ".git"
      - ".idea"
      - "status.csv"
    patterns:
      - ".*\\.unzip"
      - ".*\\.class"

word:
  guard:
    values:
      - "ibm"
      - "RuntimeException"
    patterns:
    valueFiles:
      - src/test/resources/config/word-guard-value.csv
    patternFiles:
      - src/test/resources/config/word-guard-pattern.csv

  ignore:
    values:
      - "localhost"
      - "127.0.0.1"

replace:
  values:
    "ibm": "vvv1"
  valueFiles:
    - src/test/resources/config/word-guard-value.csv

write:
  folder: target/replaced
#  report: report.csv
#  generatedReplacement: generated-replacement.csv

#manual:
#overrides:
#rules:
