read:
  folder: "."
  guard:
    values:
    patterns:
      - ".*"
  ignore:
    values:
      - "target"
      - ".git"
      - ".idea"
      - "code-report.csv"
    patterns:
      - ".*\\.unzip"
      - ".*\\.class"

word:
  guard:
    values:
      - "ibm"
      - "RuntimeException"
    patterns:
    valueFiles:
      - src/test/resources/config/word-guard-value.csv
    patternFiles:
      - src/test/resources/config/word-guard-pattern.csv

  ignore:
    values:
      - "localhost"
      - "127.0.0.1"

replace:
  values:
    "ibm": "vvv1"
  valueFiles:
    - src/test/resources/config/word-guard-value.csv

# Manual override for false-positives
allow:
  reportFiles:
    - src/test/resources/config/allow-report.csv
    - target/code-report.csv # results from previous run, overridden after rerun, so manual changes in it can be lost

write:
  folder: target/replaced
  report: target/code-report.csv

#  generatedReplacement: generated-replacement.csv

#ignore-escalate
