read:
  # !!! Project folder to be scanned - provide actual value !!!
  folder: "/work/project/scanned-sample"

  guard:
    # file folder (ending with '/') and file name patterns to include in scan
    # wildcards: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html
    values:
      - "**/*/"
      - "**/*"
    valuesFiles: [ ]
  ignore:
    # file folder and file name patterns to exclude from scan
    values:
      - "**/.git/"
      - "**/.idea/"
      - "**/target/"
      - "**/*.unzip/"
      - "**/*.bin"
      - "**/*.class"
      - "**/*.dll"
      - "**/*.exe"
      - "**/*.ico"
      - "**/*.gif"
      - "**/*.jpg"
      - "**/*.mp4"
      - "**/*.png"
      - "**/*.pyc"
      - "**/*.rpm"
      - "**/*.so"
      - "**/code-report.csv"
      - "**/.attach_pid*"
    valuesFiles:
      - "${scan.config}/file-ignore.csv"

word:
  guard:
    values: { }
    ## Mappings of "from" and "to" word replacements. "To" can be empty, will be generated. Examples:
    # "acme": "testCompany"
    # "akka": ""
    patterns:
      ## Mappings of "from" and "to" pattern replacements. "To" can contain template variables, can be empty.
      "[\\w[\\w.-]+@\\w+(\\.\\w+)+]": "u{hash}@mail.local"
      "[\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}]": "h{hash}.domain.local"
      "[\\w[\\w.-]+\\.intra]": "h{hash}.domain.local"
    valueFiles:
      # Long list of words can be extracted to separate files in config folder
      - "${scan.config}/word-guard-value.csv"
    patternFiles:
      # Long list of patterns can be extracted to separate files in config folder
      - "${scan.config}/word-guard-pattern.csv"

  ignore:
    values:
      - "localhost"
      - "127.0.0.1"
      - "0.0.0.0"
    patterns: # ignore pattern is searched, use ^..$ to match complete word
      - "@mail.local$"
    valueFiles: [ ]
    patternFiles: [ ]


# Manual override for false-positives
allow:
  reportFiles:
    - ${scan.config}/allow-report.csv # common false-positives, utilizing narrowed context, file path patterns
    - ${scan.config}/allow-report-lines.csv # collect one-time false-positives in config folder, copy-pasted from report
#    - ${write.report} # results from previous run, overridden after rerun, cleaned by maven, so manual changes in it can be lost

csv:
  enabled: false
  files: [ ]
## CSV configuration per file type
## File path is matched with wildcards
#    - filename: *accounts.csv
## Columns to replace with fill patterns
#      columns:
#        "shortName": "sn{id}" # fill by pattern
#        "longName": "ln{id}"
#        "email": ""           # clean
#        "address": "NA"       # fill with static value
